// The South Col route and the Lhotse and Nuptse branches, loaded from assets/route.json (generated by
// least-cost pathfinding over the DEM; Nuptse's line is authored for gameplay).
import { TERRAIN } from '../config.js';
import { clamp, lerp } from '../core/math.js';
import { SegmentIndex } from '../core/spatial.js';
import { PEAKS } from './geo.js';

export const CLIMBS = [
  { id: 'everest', route: 'main', short: 'Everest', minElevation: 8835, points: 1000, color: 0xff3b1f, mapColor: '#ff4a2a' },
  { id: 'lhotse', route: 'lhotse', short: 'Lhotse', minElevation: 8500, points: 700, color: 0x1fa8ff, mapColor: '#1fa8ff', junction: 'yellowband' },
  { id: 'nuptse', route: 'nuptse', short: 'Nuptse', minElevation: 7845, points: 500, color: 0xc46bff, mapColor: '#c46bff', junction: 'c2' },
].map((c) => ({ ...c, ...PEAKS.find((p) => p.id === c.id) }));
export const reachedSummits = (stats) => CLIMBS.filter((c) => stats.summits[c.id]);

export class Route {
  constructor(name, data) {
    this.name = name;
    this.pts = data.points.map(([x, z]) => ({ x, z }));
    this.tags = data.tags;
    this.cum = [0];
    for (let i = 1; i < this.pts.length; i++) {
      this.cum.push(this.cum[i - 1] + Math.hypot(this.pts[i].x - this.pts[i - 1].x, this.pts[i].z - this.pts[i - 1].z));
    }
    this.L = this.cum[this.cum.length - 1];
    const segs = [];
    for (let i = 0; i < this.pts.length - 1; i++) segs.push({ ax: this.pts[i].x, az: this.pts[i].z, bx: this.pts[i + 1].x, bz: this.pts[i + 1].z, i });
    this.index = new SegmentIndex(segs, 50);
  }
  s(tag) { return this.cum[this.tags[tag]]; }
  point(tag) { return this.pts[this.tags[tag]]; }
  /** position and unit direction at distance s along the route */
  at(s) {
    s = clamp(s, 0, this.L);
    let lo = 0, hi = this.cum.length - 1;
    while (hi - lo > 1) { const m = (lo + hi) >> 1; if (this.cum[m] <= s) lo = m; else hi = m; }
    const a = this.pts[lo], b = this.pts[hi], seg = this.cum[hi] - this.cum[lo] || 1, t = (s - this.cum[lo]) / seg;
    return { x: lerp(a.x, b.x, t), z: lerp(a.z, b.z, t), dx: (b.x - a.x) / seg, dz: (b.z - a.z) / seg, i: lo };
  }
  /** nearest point within maxDist metres, or null */
  nearestWithin(x, z, maxDist) {
    const h = this.index.nearest(x, z, maxDist);
    if (!h) return null;
    const i = this.index.segs[h.k].i;
    return { d: h.d, s: this.cum[i] + h.t * (this.cum[i + 1] - this.cum[i]), i };
  }
  /** nearest point on the route (horizontal); hint = previous index for a fast local search */
  nearest(x, z, hint = -1, window = 60) {
    if (hint < 0) return this.nearestWithin(x, z, Infinity);   // spatial index instead of a full scan
    let best = 1e18, bs = 0, bi = 0;
    const i0 = hint >= 0 ? Math.max(0, hint - window) : 0, i1 = hint >= 0 ? Math.min(this.pts.length - 1, hint + window) : this.pts.length - 1;
    for (let i = i0; i < i1; i++) {
      const a = this.pts[i], b = this.pts[i + 1], dx = b.x - a.x, dz = b.z - a.z, l2 = dx * dx + dz * dz || 1;
      const t = clamp(((x - a.x) * dx + (z - a.z) * dz) / l2, 0, 1);
      const d = (a.x + dx * t - x) ** 2 + (a.z + dz * t - z) ** 2;
      if (d < best) { best = d; bs = this.cum[i] + t * Math.sqrt(l2); bi = i; }
    }
    return { d: Math.sqrt(best), s: bs, i: bi };
  }
}

// Camp definitions. Pads are [flat radius, falloff] in metres; stock = full oxygen bottles.
export const CAMP_DEFS = [
  { id: 'ebc', route: 'main', name: 'Everest Base Camp', short: 'EBC', stock: Infinity, pad: [42, 25], tents: 40, spread: 70 },
  { id: 'c1', route: 'main', name: 'Camp 1', short: 'C1', stock: 0, pad: [16, 14], tents: 10, spread: 22 },
  { id: 'c2', route: 'main', name: 'Camp 2 · Advanced Base Camp', short: 'C2', stock: 4, pad: [26, 18], tents: 18, spread: 34 },
  { id: 'c3', route: 'main', name: 'Camp 3 · Lhotse Face', short: 'C3', stock: 3, pad: [8, 10], tents: 6, spread: 10 },
  { id: 'c4', route: 'main', name: 'Camp 4 · South Col', short: 'C4', stock: 2, pad: [24, 18], tents: 14, spread: 32 },
  { id: 'lhotse_c4', route: 'lhotse', name: 'Lhotse Camp 4', short: 'LC4', stock: 1, pad: [7, 8], tents: 4, spread: 8 },
  { id: 'nuptse_c3', route: 'nuptse', name: 'Nuptse High Camp', short: 'NC3', stock: 2, pad: [8, 10], tents: 5, spread: 10 },
];

export const LANDMARKS = {
  icefall_mid: 'The heart of the Khumbu Icefall — seracs and crevasses. Cross only on the ladders.',
  icefall_top: 'Top of the Icefall. The Western Cwm opens ahead, walled by Everest (left) and Nuptse (right).',
  bergschrund: 'The bergschrund at the foot of the Lhotse Face — 1,100 m of blue ice. Clip into the fixed ropes [E].',
  yellowband: 'The Yellow Band. Everest climbers traverse left to the Geneva Spur; Lhotse climbers go right, up the face.',
  geneva: 'The Geneva Spur — the black rock buttress. The South Col is just over the top.',
  triangular: 'The Triangular Face. A long, steep climb in the dark to the Balcony.',
  balcony: 'The Balcony, 8,400 m, on the Southeast Ridge. Change bottles here if you need to.',
  southsummit: 'The South Summit, 8,749 m. Ahead: the cornice traverse along the knife-edge ridge.',
  hillary: 'The Hillary Step, 8,790 m. A misstep right drops 3,000 m down the Kangshung Face.',
  lhotse_c4: 'Lhotse Camp 4, at the foot of the Reiss Couloir.',
  couloir: 'The Lhotse (Reiss) Couloir — a narrow gully of snow and rock straight to the summit.',
  nuptse_bergschrund: 'Nuptse north face. Clip into the purple fixed ropes [E] before climbing above the Western Cwm.',
  nuptse_c3: 'Nuptse High Camp. Rest and prepare for the north rib and summit push.',
  nuptse_rib: 'Nuptse north rib — steep, exposed snow and rock. Stay clipped all the way to the summit.',
};

export async function loadRoutes() {
  const res = await fetch(TERRAIN.routeUrl);
  if (!res.ok) throw new Error('Could not load route.json');
  const data = await res.json();
  return Object.fromEntries(CLIMBS.map(({ route }) => [route, new Route(route, data[route])]));
}

export function campsFor(routes) {
  return CAMP_DEFS.map((d) => {
    const r = routes[d.route], i = r.tags[d.id];
    return { ...d, x: r.pts[i].x, z: r.pts[i].z, routeIndex: Object.keys(routes).indexOf(d.route), pointIndex: i, s: r.cum[i] };
  });
}

/** Fixed-rope sections as [route, startDistance, endDistance] */
export function ropeDefs(routes) {
  const m = routes.main, l = routes.lhotse, n = routes.nuptse;
  return [
    { name: 'Icefall fixed lines', route: m, s0: m.s('ebc') + 240, s1: m.s('icefall_top') + 60, color: 0x2f7bff },
    { name: 'Lhotse Face fixed ropes', route: m, s0: m.s('bergschrund') - 25, s1: m.s('c4') - 30, color: 0xff3030 },
    { name: 'Summit ropes', route: m, s0: m.s('c4') + 30, s1: m.L - 1, color: 0x30c060 },
    { name: 'Lhotse Couloir fixed ropes', route: l, s0: 2, s1: l.L - 1, color: 0xffa020 },
    { name: 'Nuptse approach fixed line', route: n, s0: 2, s1: n.s('nuptse_bergschrund') + 5, color: 0xc46bff },
    { name: 'Nuptse north face fixed ropes', route: n, s0: n.s('nuptse_bergschrund') - 60, s1: n.L - 1, color: 0xc46bff },
  ];
}

/** Human-readable name of the part of the mountain at (x, z). */
export function regionName(routes, camps, x, z, y) {
  const m = routes.main, l = routes.lhotse, n = routes.nuptse;
  for (const c of CLIMBS) {
    const p = routes[c.route].pts.at(-1);
    if (Math.hypot(x - p.x, z - p.z) < 15 && y > c.minElevation) return `Summit of ${c.name}`;
  }
  for (const c of camps) if (Math.hypot(c.x - x, c.z - z) < (c.id === 'ebc' ? 70 : 32)) return c.name;
  const FAR = { d: Infinity, s: 0 };
  const nm = m.nearestWithin(x, z, 260) || FAR, nl = l.nearestWithin(x, z, 210) || FAR, nn = n.nearestWithin(x, z, 210) || FAR;
  if (nn.d < Math.min(nm.d, nl.d) && nn.d < 200 && nn.s > 25) {
    return nn.s < n.s('nuptse_bergschrund') ? 'Western Cwm · Nuptse approach' : nn.s < n.s('nuptse_rib') ? 'Nuptse North Face' : 'Nuptse North Rib';
  }
  if (nl.d < nm.d && nl.d < 200 && nl.s > 25) return nl.s > l.s('lhotse_c4') ? 'Lhotse Couloir' : 'Upper Lhotse Face';
  if (nm.d < 250) {
    const s = nm.s;
    if (s < m.s('icefall_top')) return 'Khumbu Icefall';
    if (s < m.s('bergschrund')) return 'Western Cwm';
    if (s < m.s('yellowband') - 60) return 'Lhotse Face';
    if (s < m.s('geneva') - 40) return 'Yellow Band';
    if (s < m.s('c4') - 40) return 'Geneva Spur';
    if (s < m.s('c4') + 60) return 'South Col';
    if (s < m.s('balcony') - 30) return 'Triangular Face';
    if (s < m.s('southsummit') - 20) return 'Southeast Ridge';
    if (s < m.s('hillary') - 10) return 'Cornice traverse';
    return 'Summit ridge';
  }
  if (y > 7000) return x < -2200 && z > 1000 ? 'Nuptse' : x > 400 ? 'Kangshung Face' : z < 600 ? 'Southwest Face of Everest' : z > 2200 ? 'Lhotse' : 'Lhotse Face';
  return y > 5900 ? 'Western Cwm' : 'Khumbu Glacier';
}
