#!/usr/bin/env python3
"""Build the game's terrain and route assets from the Copernicus GLO-30 DEM.

Usage:
    python3 tools/build_assets.py --dem /path/to/copernicus/tiles

The DEM folder must contain the four 1x1 degree GeoTIFF tiles
N27_00_E086_00.tif, N28_00_E086_00.tif, N27_00_E087_00.tif, N28_00_E087_00.tif
downloaded from https://copernicus-dem-30m.s3.amazonaws.com/ (see README).

Outputs (in assets/):
    terrain/core.png      15 m grid of the climbing area (RG = height * 4, B = glacier mask)
    terrain/backdrop.png  160 m grid of the surrounding Khumbu / Mahalangur Himal
    terrain/meta.json     grid extents and encoding
    route.json            the South Col route and the Lhotse branch, generated by
                          least-cost pathfinding over the real terrain between surveyed waypoints
"""
import argparse, heapq, json, math, os
import numpy as np
from scipy.ndimage import gaussian_filter, uniform_filter, map_coordinates
from demlib import Mosaic, grid, encode_png, ll_to_xz

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORE = dict(x0=-10240, z0=-4608, cell=15, nx=1025, nz=769)
BACK = dict(x0=-46080, z0=-40960, cell=160, nx=577, nz=513)

# True summit elevations. The 30 m DEM rounds off sharp summits by 70-130 m. Each summit is
# corrected by stretching only the upper part of the mountain (weighted by elevation), so the
# DEM's own ridges and faces are kept and simply sharpened toward the surveyed height.
PEAKS = [
    ('Mount Everest', 27.988056, 86.925278, 8849),
    ('Lhotse', 27.961667, 86.933056, 8516),
    ('Lhotse Shar', 27.961389, 86.945000, 8383),
    ('Nuptse', 27.967000, 86.886000, 7861),
    ('Pumori', 28.014700, 86.828100, 7161),
    ('Changtse', 28.024400, 86.914200, 7543),
    ('Makalu', 27.889444, 87.088889, 8485),
    ('Cho Oyu', 28.094167, 86.660833, 8188),
    ('Gyachung Kang', 28.098100, 86.742200, 7952),
    ('Ama Dablam', 27.861667, 86.861389, 6812),
    ('Baruntse', 27.871667, 86.981667, 7129),
    ('Island Peak', 27.922800, 86.936100, 6189),
    ('Lobuche East', 27.956700, 86.810600, 6119),
]

# Surveyed waypoints (world metres, origin = Everest summit, x east, z south).
# Positions follow published route descriptions and were checked against the DEM:
# the route climbs ESE through the Icefall, keeps to the north (Everest) side of the
# Western Cwm, goes up the Lhotse Face to Camp 3, traverses left (north-east) across the
# Yellow Band to the Geneva Spur and the South Col, then climbs the Triangular Face to the
# Balcony and follows the Southeast Ridge over the South Summit and Hillary Step.
MAIN_WAYPOINTS = [
    ('ebc', -6350, -1050), (None, -6000, -980), (None, -5600, -930), ('icefall_mid', -5250, -820),
    (None, -5000, -560), ('icefall_top', -4850, -250), ('c1', -4650, 150),
    (None, -4000, 430), (None, -3250, 600), ('c2', -2450, 680),
    (None, -1850, 980), (None, -1500, 1300), ('bergschrund', -1250, 1500),
    (None, -900, 1620), ('c3', -600, 1700), (None, -380, 1720), ('yellowband', -170, 1700),
    (None, 20, 1600), ('geneva', 200, 1480), (None, 360, 1470), ('c4', 600, 1580),
    (None, 470, 1380), ('triangular', 360, 1170), (None, 280, 900), ('balcony', 230, 600),
]
# above the Balcony the route follows the Southeast Ridge crest traced from the DEM
LHOTSE_WAYPOINTS = [
    ('yellowband', -170, 1700), (None, -60, 1900), (None, 120, 2200),
    ('lhotse_c4', 380, 2450), ('couloir', 520, 2620), (None, 640, 2760), ('lhotse', None, None),
]
# Profile of the summit ridge (distance along the crest from the summit -> elevation)
RIDGE_PROFILE = [(0, 8849), (85, 8790), (100, 8772), (200, 8736), (250, 8749)]
BALCONY_ELEV = 8400


def local_max(h, g, x, z, radius):
    c0 = int(round((x - g['x0']) / g['cell'])); r0 = int(round((z - g['z0']) / g['cell']))
    rr = int(math.ceil(radius / g['cell']))
    sub = h[max(0, r0 - rr):r0 + rr + 1, max(0, c0 - rr):c0 + rr + 1]
    if sub.size == 0: return None
    j, i = np.unravel_index(np.argmax(sub), sub.shape)
    return (g['x0'] + (max(0, c0 - rr) + i) * g['cell'], g['z0'] + (max(0, r0 - rr) + j) * g['cell'], float(sub[j, i]))


def _smooth(a, b, x):
    t = np.clip((x - a) / (b - a), 0, 1); return t * t * (3 - 2 * t)


def stretch_peak(h, g, peak, target, radius, band):
    """Raise the top `band` metres of a mountain so its summit reaches `target`."""
    x, z, top = peak
    xs = g['x0'] + np.arange(g['nx']) * g['cell']; zs = g['z0'] + np.arange(g['nz']) * g['cell']
    X, Z = np.meshgrid(xs, zs)
    d = np.hypot(X - x, Z - z)
    w = (1 - _smooth(0.45 * radius, radius, d)) * _smooth(top - band, top, h) ** 1.4
    h += (target - top) * w


def sample(h, g, x, z, order=1):
    return map_coordinates(h, [(np.asarray(z) - g['z0']) / g['cell'], (np.asarray(x) - g['x0']) / g['cell']], order=order, mode='nearest')


def trace_crest(h, g, start, z_end):
    """Follow the Southeast Ridge crest south from the summit by tracking the local maximum."""
    x, z, _ = start; pts = [(x, z)]
    while z < z_end:
        z += 10
        xs = np.arange(x - 30, x + 31, 5.0)
        hs = sample(h, g, xs, np.full_like(xs, z), order=3)
        x = float(xs[int(np.argmax(hs))]); pts.append((x, z))
    return np.array(pts)


def correct_summit_ridge(h, g, band=300.0):
    top = local_max(h, g, 0, 0, 150)
    crest = trace_crest(h, g, top, 600)
    seg = np.hypot(np.diff(crest[:, 0]), np.diff(crest[:, 1])); s = np.concatenate([[0], np.cumsum(seg)])
    dem = sample(h, g, crest[:, 0], crest[:, 1], order=3)
    ps, pe = zip(*RIDGE_PROFILE)
    want = np.where(s <= ps[-1], np.interp(s, ps, pe), np.interp(s, [ps[-1], s[-1]], [pe[-1], BALCONY_ELEV]))
    delta = np.maximum(0, want - dem)
    # each grid point takes the correction of its nearest crest point, weighted by how close it is
    # to the crest's elevation there - faces below the crest stay as the DEM has them
    xs = g['x0'] + np.arange(g['nx']) * g['cell']; zs = g['z0'] + np.arange(g['nz']) * g['cell']
    i0, i1 = np.searchsorted(xs, crest[:, 0].min() - 250), np.searchsorted(xs, crest[:, 0].max() + 250)
    j0, j1 = np.searchsorted(zs, crest[:, 1].min() - 250), np.searchsorted(zs, crest[:, 1].max() + 250)
    X, Z = np.meshgrid(xs[i0:i1], zs[j0:j1])
    best_d = np.full(X.shape, 1e9); best_dh = np.zeros(X.shape); best_ch = np.zeros(X.shape)
    for k in range(len(crest) - 1):
        ax, az = crest[k]; bx, bz = crest[k + 1]; dx, dz = bx - ax, bz - az; l2 = dx * dx + dz * dz
        t = np.clip(((X - ax) * dx + (Z - az) * dz) / l2, 0, 1)
        d = np.hypot(ax + dx * t - X, az + dz * t - Z)
        m = d < best_d; best_d[m] = d[m]; best_dh[m] = (delta[k] + (delta[k + 1] - delta[k]) * t)[m]
        best_ch[m] = (dem[k] + (dem[k + 1] - dem[k]) * t)[m]
    sub = h[j0:j1, i0:i1]
    w = _smooth(best_ch - band, best_ch, sub) ** 1.4 * (1 - _smooth(150, 260, best_d))
    h[j0:j1, i0:i1] = sub + best_dh * w
    return crest, s


def glacier_mask(h, g):
    """Valley glaciers: gentle, concave terrain below 7,000 m (plus the whole Khumbu/Western Cwm)."""
    slope = np.hypot(*np.gradient(h, g['cell']))
    concave = uniform_filter(h, size=31) - h
    m = (slope < 0.36).astype(float) * np.clip((concave + 25) / 40, 0, 1) * (h < 7000)
    return np.clip(gaussian_filter(m, 1.5), 0, 1)


def astar(h, g, a, b, corridor=None, slope=None, penalty=None):
    """Least-cost path on the grid. Cost penalises steep path grades and steep side slopes,
    the way climbers pick lines; waypoints keep it on the real route."""
    cell = g['cell']; nz, nx = h.shape
    if slope is None:
        gy, gx = np.gradient(h, cell); slope = np.hypot(gx, gy)
    def ij(p): return (int(round((p[1] - g['z0']) / cell)), int(round((p[0] - g['x0']) / cell)))
    s, t = ij(a), ij(b)
    pad = 60
    j0, j1 = max(0, min(s[0], t[0]) - pad), min(nz - 1, max(s[0], t[0]) + pad)
    i0, i1 = max(0, min(s[1], t[1]) - pad), min(nx - 1, max(s[1], t[1]) + pad)
    dist = {s: 0.0}; prev = {}; pq = [(0.0, s)]
    nb = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]
    while pq:
        f, u = heapq.heappop(pq)
        if u == t: break
        du = dist[u]
        if f - math.hypot(u[0] - t[0], u[1] - t[1]) * cell > du + 1e-6: continue
        for dj, di in nb:
            v = (u[0] + dj, u[1] + di)
            if not (j0 <= v[0] <= j1 and i0 <= v[1] <= i1): continue
            run = cell * (1.41421356 if dj and di else 1.0)
            grade = (h[v] - h[u]) / run
            sl = slope[v]
            c = run * (1 + 2.2 * grade * grade + 0.6 * sl * sl + 40 * max(0.0, sl - 1.3) ** 2)
            if penalty is not None:
                c *= penalty[v]
            nd = du + c
            if nd < dist.get(v, 1e18):
                dist[v] = nd; prev[v] = u
                heapq.heappush(pq, (nd + math.hypot(v[0] - t[0], v[1] - t[1]) * cell, v))
    path = [t]
    while path[-1] != s: path.append(prev[path[-1]])
    path.reverse()
    return [(g['x0'] + p[1] * cell, g['z0'] + p[0] * cell) for p in path]


def smooth_resample(pts, step=4.0, iters=3):
    p = np.array(pts, float)
    for _ in range(iters):  # Chaikin corner cutting, endpoints kept
        q = [p[0]]
        for k in range(len(p) - 1):
            q.append(0.75 * p[k] + 0.25 * p[k + 1]); q.append(0.25 * p[k] + 0.75 * p[k + 1])
        q.append(p[-1]); p = np.array(q)
    seg = np.hypot(*np.diff(p, axis=0).T); s = np.concatenate([[0], np.cumsum(seg)])
    ss = np.arange(0, s[-1], step); ss = np.append(ss, s[-1])
    out = np.stack([np.interp(ss, s, p[:, 0]), np.interp(ss, s, p[:, 1])], 1)
    # remove the remaining grid staircase (sigma ~ 12 m), keeping both ends fixed
    sm = np.stack([gaussian_filter(out[:, 0], 3, mode='nearest'), gaussian_filter(out[:, 1], 3, mode='nearest')], 1)
    w = np.clip(np.minimum(np.arange(len(out)), np.arange(len(out))[::-1]) / 6.0, 0, 1)[:, None]
    return out * (1 - w) + sm * w


def build_route(h, g, waypoints, tail=None, slope=None, penalty=None):
    pts, tags = [], []
    for k in range(len(waypoints) - 1):
        a, b = waypoints[k], waypoints[k + 1]
        seg = astar(h, g, a[1:], b[1:], slope=slope, penalty=penalty)
        if pts: seg = seg[1:]
        pts += seg
    if tail is not None:
        pts += [tuple(p) for p in tail[1:]]
    path = smooth_resample(pts)
    # tag each waypoint at the nearest resampled point
    for wp in waypoints:
        if wp[0] is None: continue
        d = np.hypot(path[:, 0] - wp[1], path[:, 1] - wp[2]); tags.append((wp[0], int(np.argmin(d))))
    return path, dict(tags)


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--dem', required=True); args = ap.parse_args()
    mos = Mosaic(args.dem)
    out = os.path.join(ROOT, 'assets'); os.makedirs(os.path.join(out, 'terrain'), exist_ok=True)

    print('sampling core grid…'); core = grid(mos, CORE['x0'], CORE['z0'], CORE['cell'], CORE['nx'], CORE['nz'])
    print('sampling backdrop grid…'); back = grid(mos, BACK['x0'], BACK['z0'], BACK['cell'], BACK['nx'], BACK['nz'])

    crest, crest_s = correct_summit_ridge(core, CORE)
    report = {}
    for name, lat, lon, elev in PEAKS:
        x, z = ll_to_xz(lat, lon)
        for h, g, sig, tag in ((core, CORE, 55, 'core'), (back, BACK, 260, 'back')):
            if not (g['x0'] < x < g['x0'] + (g['nx'] - 1) * g['cell'] and g['z0'] < z < g['z0'] + (g['nz'] - 1) * g['cell']): continue
            if tag == 'core' and name == 'Mount Everest': continue      # handled by the ridge correction
            m = local_max(h, g, x, z, 450 if tag == 'core' else 900)
            if m and m[2] < elev:
                stretch_peak(h, g, m, elev, radius=600 if tag == 'core' else 1500, band=320 if tag == 'core' else 600)
            report.setdefault(name, {})[tag] = round(float(local_max(h, g, x, z, 450 if tag == 'core' else 900)[2]))
    for k, v in report.items(): print(f'  {k:14s} {v}')

    gm = glacier_mask(core, CORE)
    # Khumbu Glacier / Western Cwm centre line is always glacier
    khumbu = [(-1300, 1500), (-2450, 650), (-4650, 200), (-5300, -750), (-6500, -1150), (-7600, -1000), (-8600, -200), (-9300, 1200), (-9700, 3500)]
    xs = CORE['x0'] + np.arange(CORE['nx']) * CORE['cell']; zs = CORE['z0'] + np.arange(CORE['nz']) * CORE['cell']
    X, Z = np.meshgrid(xs, zs); dmin = np.full(X.shape, 1e9)
    for (ax, az), (bx, bz) in zip(khumbu[:-1], khumbu[1:]):
        dx, dz = bx - ax, bz - az; t = np.clip(((X - ax) * dx + (Z - az) * dz) / (dx * dx + dz * dz), 0, 1)
        dmin = np.minimum(dmin, np.hypot(ax + dx * t - X, az + dz * t - Z))
    slope = np.hypot(*np.gradient(core, CORE['cell']))
    gm = np.maximum(gm, np.clip((380 - dmin) / 120, 0, 1) * (slope < 0.45))

    # route: A* over the corrected terrain, then the traced summit ridge
    bi = int(np.argmin(np.hypot(crest[:, 0] - 230, crest[:, 1] - 600)))
    ridge = crest[:bi + 1][::-1]            # Balcony -> summit
    main_path, main_tags = build_route(core, CORE, MAIN_WAYPOINTS, tail=ridge)
    d = np.hypot(main_path[:, 0] - ridge[-1][0], main_path[:, 1] - ridge[-1][1]); main_tags['everest'] = int(np.argmin(d))
    for tag, s_target in (('southsummit', 250), ('hillary', 90)):
        k = int(np.argmin(np.abs(crest_s - s_target))); p = crest[k]
        main_tags[tag] = int(np.argmin(np.hypot(main_path[:, 0] - p[0], main_path[:, 1] - p[1])))
    lx, lz = ll_to_xz(27.961667, 86.933056); lm = local_max(core, CORE, lx, lz, 450)
    lw = [w if w[0] != 'lhotse' else ('lhotse', lm[0], lm[1]) for w in LHOTSE_WAYPOINTS]
    lh_path, lh_tags = build_route(core, CORE, lw)

    encode_png(core, os.path.join(out, 'terrain', 'core.png'))
    # glacier mask into the blue channel
    from PIL import Image
    im = np.array(Image.open(os.path.join(out, 'terrain', 'core.png')))
    im[..., 2] = np.round(gm * 255).astype(np.uint8)
    Image.fromarray(im, 'RGB').save(os.path.join(out, 'terrain', 'core.png'), optimize=True)
    encode_png(back, os.path.join(out, 'terrain', 'backdrop.png'))
    meta = dict(encoding='height = (R * 256 + G) / 4 metres; B = glacier mask (core only)',
                origin=dict(lat=27.988056, lon=86.925278, note='Mount Everest summit; x = east, z = south'),
                source='Copernicus GLO-30 DEM (ESA, distributed by AWS Open Data), summit elevations corrected to surveyed values',
                runtime=dict(refine=2, proceduralDetail=True), core=CORE, backdrop=BACK)
    json.dump(meta, open(os.path.join(out, 'terrain', 'meta.json'), 'w'), indent=1)

    def elev(p): return float(sample(core, CORE, [p[0]], [p[1]], order=1)[0])
    route = dict(
        note='Generated by tools/build_assets.py: least-cost path over the DEM between surveyed waypoints.',
        main=dict(points=[[round(float(x), 1), round(float(z), 1)] for x, z in main_path], tags=main_tags),
        lhotse=dict(points=[[round(float(x), 1), round(float(z), 1)] for x, z in lh_path], tags=lh_tags))
    json.dump(route, open(os.path.join(out, 'route.json'), 'w'))
    for name, path, tags in (('main', main_path, main_tags), ('lhotse', lh_path, lh_tags)):
        L = float(np.sum(np.hypot(*np.diff(path, axis=0).T)))
        print(f'{name}: {len(path)} pts, {L / 1000:.2f} km')
        for t, i in sorted(tags.items(), key=lambda kv: kv[1]): print(f'   {t:12s} #{i:5d}  {elev(path[i]):7.0f} m  ({path[i][0]:.0f}, {path[i][1]:.0f})')


if __name__ == '__main__':
    main()
